version: '3.9'
services:
  backend:
    image: taki-backend:latest
    build:
        context: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-toor}
      POSTGRES_DB: ${DB_NAME:-defaultdb}
    networks:
      - db
    ports:
      - "8082:8080"
    restart: unless-stopped

  frontend:
    image: taki-frontend:latest
    build:
      context: ./frontend
    ports:
      - "4280:80"
    networks:
      - db
    restart: unless-stopped

  database:
    container_name: taki_database
    image: postgres:15.2-alpine
    restart: always
    networks:
      - db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-toor}
      POSTGRES_DB: ${DB_NAME:-defaultdb}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DB_USERNAME:-root} -d ${DB_NAME:-defaultdb}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  db:
volumes:
  db-data:
